### ISSUE TITLE
Move to GitLab

### ISSUE THREAD

**Issue by wavexx** [wavexx/Expect.jl#5]
I'll be moving my source repositories to GitLab (https://gitlab.com/wavexx/) during the next few days.

I've been waiting to do this for a long time (at least since 2015) but I never switched because of network effects. I'll now use the acquisition news as an excuse to jump the shark!

This repository will be turned into a read-only archive after the migration and effectively become stale.
Since all issues and PR will be mirrored on gitlab, I'll also close all of them in github and reference this issue to make sure this is not going to be ignored. 

See you on the other side!

**Comment by PerezHz** [comment]
Hi, @wavexx! @tkluck has been trying to update Expect.jl to julia 0.7/1.0 (see #6), but I just remembered this notice; so, could you please confirm that you have moved the latest version of Expect.jl into GitLab? I've been searching for it and couldn't find it on GitLab :( thanks in advance!

**Comment by wavexx** [comment]
Migrated now.
